[book]
authors = ["GYoung"]
language = "en"
multilingual = false
src = "src"
title = "rust_kr"

[output.html]
git-repository-url = "https://github.com/YoungHaKim7/rust_kr"
git-repository-icon = "fa-github"


[output.html.playground]
runnable = true
editable = true

[output.html.search]
limit-results = 10

[output.html.fold]
enable = true
level = 0
